[project]
name = "dataupdater"
version = "0.1.2"
description = "A live Python variable editor via web interface"
authors = [{ name="Anson", email="ansonwong815@email.com" }]
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }

[tool.setuptools.packages.find]
where = ["dataupdater"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"