[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "proxar"
version = "0.3.0"
description = "A Python client for fetching public proxies from multiple sources."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.13",
    "platformdirs>=4.3.8",
    "types-aiofiles>=24.1.0.20250606",
]
license = {file = "LICENSE"}
authors = [
    {name = "Filming"}
]
keywords = ["python", "python3", "proxy", "proxies", "web-scraping", "asyncio"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[project.urls]
Homepage = "https://github.com/filming/proxar"
Repository = "https://github.com/filming/proxar"
Issues = "https://github.com/filming/proxar/issues"
Changelog = "https://github.com/filming/proxar/blob/master/CHANGELOG.md"

[tool.ruff]
line-length = 88
target-version = "py310"
src = ["src"]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "PL", "B", "SIM", "C90"]
ignore = []

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.isort]
known-first-party = ["proxar"]

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
strict = true
files = ["src"]
python_version = "3.10"

[tool.pdm.scripts]
format = "uv run ruff format src"
check_fix = "uv run ruff check --fix src"
type_check = "uv run mypy src"
clean = { composite = ["format", "check_fix", "type_check"] }

[tool.hatch.build.targets.wheel]
packages = ["src/proxar"]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "pep440"
version_provider = "uv"
update_changelog_on_bump = true
changelog_message_builder_hook = "commitizen.hooks.conventional_commits_message_builder_hook"
change_type_map = { "feat" = "Features", "fix" = "Bug Fixes", "perf" = "Performance Improvements", "refactor" = "Code Refactoring", "build" = "Build System", "ci" = "Continuous Integration", "docs" = "Documentation", "style" = "Styles", "test" = "Tests", "chore" = "Chores" }

[dependency-groups]
dev = [
    "commitizen>=4.8.3",
    "mypy>=1.16.1",
    "pdm>=2.25.3",
    "pre-commit>=4.2.0",
    "ruff>=0.12.1",
]
