[project]
name = "pyleak"
version = "0.1.13"
description = "Detect leaked asyncio tasks, threads, and event loop blocking in Python. Inspired by Go's goleak"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "exceptiongroup>=1.3.0",
]
authors = [
    { name = "Deepankar Mahapatro", email = "deepankarmahapatro@gmail.com" },
]
keywords = [
    "asyncio", 
    "testing", 
    "leak", 
    "goleak",
    "async",
    "tasks",
    "threads",
    "pytest"
]

[project.urls]
"Homepage" = "https://github.com/deepankarm/pyleak"
"Repository" = "https://github.com/deepankarm/pyleak"
"Issues" = "https://github.com/deepankarm/pyleak/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "aiohttp>=3.12.6",
    "fastapi>=0.115.12",
    "httpx>=0.28.1",
    "pytest>=8.3.5",
    "pytest-asyncio>=1.0.0",
    "requests>=2.32.3",
    "ruff>=0.11.12",
]

[project.entry-points."pytest11"]
pyleak = "pyleak.pytest_plugin"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
