[project]
name = "plotfig"
version = "1.0.0"
description = "Scientific plotting package for Cognitive neuroscience"
keywords = ["neuroscience", "plotting", "visualization"]
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Ricardo Ryn", email = "ricardoRyn1317@gmail.com" }
]
dependencies = [
    "matplotlib>=3.10.1",
    "mne-connectivity>=0.7.0",
    "nibabel>=5.3.2",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "scipy>=1.15.2",
    "surfplot>=0.2.0",
]

[dependency-groups]
dev = [
    "mkdocs-material>=9.6.14",
    "mkdocs-minify-plugin>=0.8.0",
    "mkdocstrings[python]>=0.29.1",
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"plotfig" = "src/plotfig"}
packages = ["plotfig"]
include-package-data = true

[tool.setuptools.package-data]
plotfig = [
    "data/atlas_tables/**/*",
    "data/neurodata/**/*"
]

[tool.ruff]
exclude = [
  "examples/example.ipynb"
]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "pep440"
version_provider = "pep621"
update_changelog_on_bump = true
# major_version_zero = true
