[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.8"
readme = "README.md"
name = "ildev-db"
version = "0.0.13"
description = "Reusable SQLite + SQLAlchemy and MongoDB + Beanie async repository module"
authors = [{name = "Ilias Aiupov"}]
dependencies = [
    "sqlalchemy[asyncio]",
    "aiosqlite",
    "beanie",
    "motor",
    "pydantic",
    "ildev-log>=0.0.3"
]

classifiers = [
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
build = ["build", "twine"]
test = ["pytest", "pytest-asyncio"]
dev = ["build", "twine", "pytest", "pytest-asyncio"]

[tool.setuptools.dynamic]
readme = { file = "README.md" }