[project]
name = "huuh-mcp"
version = "0.2.12"
description = "collaborative AI"
readme = "README.md"
authors = [
    { name = "Filipp Trigub", email = "filipp.trigub@infolab.ai" }
]
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.23.0",
    "fastmcp>=2.3.4",
    "pydantic>=2.11.4",
    "pydantic-settings>=2.0.0",
    "python-dotenv>=1.1.0",
]

[project.scripts]
huuh-mcp = "huuh_mcp.server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["huuh_mcp"]
