[project]
name = "bitgauss"
description = "A fast boolean linear algebra library"
version = "0.3.3"
requires-python = ">=3.9"
license = "Apache-2.0"
readme = "README.md"
authors = [{ name = "Aleks Kissinger", email = "aleks0@gmail.com" }]
maintainers = [
    { name = "Aleks Kissinger", email = "aleks0@gmail.com" },
]
classifiers = [
    "Environment :: Console",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
]

[build-system]
requires = ["maturin>=1.7.0"]
build-backend = "maturin"

[project.urls]
homepage = "https://github.com/akissinger/bitgauss"
repository = "https://github.com/akissinger/bitgauss"

[tool.maturin]
module-name = "bitgauss"
manifest-path = "pybindings/Cargo.toml"

[project.optional-dependencies]
test = [
    "pytest>=8.4.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --tb=short"
