[project]
name = "perfetto_extras"
version = "0.3.1"
description = ""
authors = [
    { name = "merlotliu", email = "meetlouisliu@163.com" },
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "protobuf (==5.29.3)",
    "click (>=8.2.1,<9.0.0)"
]

[project.scripts]
opentrace = "perfetto_extras.opentrace:opentrace"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
