[project]
name = "minwei-tools"
version = "0.1.19"
description = "Some useful tools for Python development by MinWei"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name="OUYANGMINWEI", email="wesley91345@gmail.com" }
]
dependencies = [
    "colorama>=0.4.6",
    "flask>=2.2.5",
]
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
"minwei_tools.server" = "minwei_tools.server:app.run"
"minwei_tools.uv_doc" = "minwei_tools.uv_doc:generate_readme"