[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "argscape"
version = "0.1.9"
description = "ARGscape: interactive ARG visualization and analysis"
readme = "README.md"
requires-python = ">=3.8"
authors = [{ name = "Chris Talbot", email = "chtalbot@umich.edu" }]
license = { file = "LICENSE" }

dependencies = [
  "numpy>=1.24.0,<2.0.0",
  "pandas",
  "tskit",
  "tszip>=0.2.3",
  "msprime",
  "scikit-learn",
  "fastapi",
  "uvicorn[standard]==0.24.0",
  "python-multipart==0.0.6",
  "python-dotenv==1.0.0",
  "apscheduler==3.10.4",
  "tsdate",
  "fastgaia",
  "geoancestry",
  "geopandas==0.14.1",
  "shapely>=2.0.2,<3.0.0",
  "pyproj",
  "fiona==1.9.5",
  "sympy",
  "scipy",
  "tqdm",
  "matplotlib",
  "pydantic"
]

[project.scripts]
argscape = "argscape.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["argscape*"]

[tool.setuptools.package-data]
"argscape" = [
    "frontend_dist/**/*",
    "backend/environment.yml",
    "backend/geo_utils/data/**/*.geojson",
    "backend/geo_utils/data/**/*.shp",
    "backend/geo_utils/data/**/*.shx", 
    "backend/geo_utils/data/**/*.dbf",
    "backend/geo_utils/data/**/*.prj",
    "backend/geo_utils/data/**/*.cpg",
    "backend/geo_utils/data/**/*.xml",
]