apiVersion: v2
name: langgate-envoy
description: Envoy proxy component for LangGate AI Gateway
version: 0.1.7
appVersion: "0.1.7"

dependencies:
  - name: langgate-helpers
    repository: file://../library/langgate-helpers
    version: 0.1.7
