[project]
name = "LlmGenJson"
version = "0.1.4"
description = "Generate JSON data using LLM"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=1.82.0",
    "python-dotenv>=1.1.0",
    "weberfuncs>=0.0.171",
]

