[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "infravision"
version = "0.0.1"
authors = [
  { name="Thomas Hansen", email="thomas@roboflow.com" },
]
description = "vision infrastructure"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 1 - Planning",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]