load:
    login_code_description: "<h3>1. ğŸ”‘ Login code: Insert the login code you received:</h3>"
    login_code_label: "Login code"
    login_code_placeholder: "Insert login code..."
    login_code_info: "If you didn't receive a login code, please contact us."
    input_description: "<h3>2. ğŸ“ Input sentences: Upload a file containing source sentences and translations in SOURCE ||| TRANSLATION format</h3>"
    file_label: "Input file"
    sentences_label: "Input sentences"
    sentences_placeholder: "Insert one sentence with format SOURCE ||| TARGET per line..."
    start_button_label: "ğŸ“ Start"
translate:
    source_side_label: "<h3>Source sentences</h3><p>These are the original sentences you need to translate.</p>"
    target_side_label: "<h3>Translations with potential issues</h3><p>These are pre-translated sentences that may require editing. Use the green checkmark to remove remaining highlights if needed.</p>"
    target_side_label_no_highlights: "<h3>Translations with potential issues</h3>"
    reload_button_label: "â¬…ï¸ Back to data loading"
    done_button_label: "âœ… Done"
    download_button_label: "ğŸ“¥ Download translations"
    source_textbox_label: "Source text"
    target_textbox_label: "Translation"
    legend_label: "Potential issue severity"
    legend_label_no_highlights: "These are pre-translated sentences that may require editing."
