[build-system]
requires = ["hatchling >=1.26", "requests", "pandas"]
build-backend = "hatchling.build"

[project]
name = "uu_battery"
version = "0.1.2"
authors = [
    { name="Abbe Tanndal", email="abbe.tanndal@gmail.com" },
]
description = "A package for interacting with the uu battery data handler project"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
UU-Battery-Data-Handler = "https://github.com/fabianwilson/UU-Battery-Data-Handler"