[project]
name = "yta-ai-leonardo"
version = "0.0.1"
description = "Youtube Autonomous AI Leonardo Module."
authors = [
    {name = "danialcala94",email = "danielalcalavalera@gmail.com"}
]
readme = "README.md"
requires-python = "==3.9"
dependencies = [
    "yta_validation (>=0.0.1,<1.0.0)",
    "yta_programming (>=0.0.1,<1.0.0)",
    "yta_general (>=0.0.1,<1.0.0)",
    "yta_constants (>=0.0.1,<1.0.0)",
    "yta_file (>=0.0.1,<1.0.0)",
]

[tool.poetry]
packages = [{include = "yta_ai_leonardo", from = "src"}]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
