[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "habitpy"
version = "0.1.13"
description = "Track your habits from the terminal"
readme = "README.md"
license = "MIT"
authors = [{ name = "SebastiÃ¡n Figueroa", email= "sebaj348@gmail.com" }]
requires-python= ">=3.11"
dependencies = [
    "pandas",
    "plotly",
    "platformdirs"
]
[projects.url]
Repository = "https://github.com/Asunt70/habitpy"
[project.scripts]
habitpy = "habitpy.habitpy:main"
