[project]
name = "zllm-kit"
version = "0.1.0"
description = "LLM quantization framework"
readme = "README.md"
authors = [
    { name = "Vladimir Malinovskii", email = "galqiwi@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
