[build-system]
requires = ["aiohttp", "asyncio", "chonkie", "cloudpickle", "deskew", "faiss-cpu", "fasttext", "lmdb", "markdown", "numpy", "ollama", "onnxruntime", "onnxruntime_extensions", "openai", "opencv-python-headless", "pandas", "Pillow", "prince", "prophet", "PyMuPDF", "pymongo", "pytesseract", "pytz", "requests", "scikit-image", "scikit-learn", "scipy", "semantic-compressor", "setuptools>=61.0", "shortuuid", "strive-ranker", "thefuzz[speedup]", "tiktoken", "tokenizers", "tqdm", "xxhash", "fastapi", "APScheduler", "bson", "uvicorn", "pydantic", "sqlalchemy", "orjson"]
build-backend = "setuptools.build_meta"

[project]
name = "llm-utility-pack"
version = "3.5"
authors = [
  { name="Carlo Moro", email="cnmoro@gmail.com" },
]
description = ""
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "cloudpickle",
  "pytz",
  "ollama",
  "requests",
  "aiohttp",
  "asyncio",
  "lmdb",
  "markdown",
  "fasttext",
  "deskew",
  "semantic-compressor",
  "PyMuPDF",
  "pytesseract",
  "opencv-python-headless",
  "scikit-image",
  "Pillow",
  "pandas",
  "scikit-learn",
  "faiss-cpu",
  "numpy",
  "thefuzz[speedup]",
  "strive-ranker",
  "shortuuid",
  "prophet",
  "prince",
  "scipy",
  "onnxruntime",
  "tokenizers",
  "tqdm",
  "chonkie",
  "pymongo",
  "openai",
  "tiktoken",
  "onnxruntime_extensions",
  "xxhash",
  "fastapi",
  "APScheduler",
  "uvicorn",
  "pydantic",
  "sqlalchemy",
  "orjson"
]