[project]
name = "ezMM"
version = "0.3.1"
description = "Lightweight Python kit for easy multimodal data processing."
readme = "README.md"
requires-python = ">=3.8"
license = "Apache-2.0"
authors = [{name = "Mark Rothermel", email = "mark.rothermel@tu-darmstadt.de"}]
dependencies = [
    "pillow",
    "pillow-avif-plugin",
    "opencv-python",
    "aiohttp",
    "uvicorn",
    "fastapi",
    "starlette"
]

[project.urls]
"Homepage" = "https://github.com/multimodal-ai-lab/ezmm"
"Bug Tracker" = "https://github.com/multimodal-ai-lab/ezmm/issues"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["ezmm*"]
exclude = ["*.egg-info", "tests*", "in*", "scripts*", "temp*"]
