# ==============================================================================
# Python pipeline for infdate
# using components
# ==============================================================================

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"


include:
  - component: $CI_SERVER_FQDN/blackstream-x/generic-components/meta-gitlab-security@~latest
  - component: $CI_SERVER_FQDN/blackstream-x/python-components/meta-uv-pipeline@feature/uv-version
    inputs:
      uv-version: "0.7.17"
      mypy-args: "--exclude tools/"
      python-version: "3.13"
      python-variant: "alpine"
      pylint-args: "--disable=fixme --report=yes"
      pytest-rules:
        - if: $CI_COMMIT_TAG == null
      pytest-matrix:
        - TEST_PYTHON_VERSION: ["3.10", "3.11", "3.12", "3.14-rc"]
      pypi-project-name: infdate


stages:
  - codestyle
  - test
  - pre-build
  - build
  - upload
