[project]
name = "infdate"
version = "0.2.5"
description = "Date object wrapper supporting infinity"
readme = "README.md"
authors = [
    { name = "Rainer Schwarzbach", email = "rainer@blackstream.de" },
]
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3 :: Only",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Intended Audience :: Developers",
]
dependencies = []

[project.urls]
Homepage = "https://gitlab.com/blackstream-x/infdate"
CI = "https://gitlab.com/blackstream-x/infdate/-/pipelines"
"Bug Tracker" = "https://gitlab.com/blackstream-x/infdate/-/issues"
Repository = "https://gitlab.com/blackstream-x/infdate.git"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
