[project]
name = "yta-audio-narration-tiktok"
version = "0.0.3"
description = "Youtube Autonomous Audio Narration Tiktok Voice Module."
authors = [
    {name = "danialcala94",email = "danielalcalavalera@gmail.com"}
]
readme = "README.md"
requires-python = "==3.9"
dependencies = [
    "yta_audio_narration_common (>=0.0.1,<1.0.0)",
    "yta_constants (>=0.0.1,<1.0.0)",
    "yta_file (>=0.0.1,<1.0.0)",
    "yta_text (>=0.0.1,<1.0.0)",
    "yta_programming (>=0.0.1,<1.0.0)",
    "requests (>=2.32.3,<9.0.0)",
]

[tool.poetry]
packages = [{include = "yta_audio_narration_tiktok", from = "src"}]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
