[project]
name = "nilai-py"
version = "0.1.1"
description = "Nilai Python SDK"
readme = "README.md"
authors = [
    { name = "JosÃ© Cabrero-Holgueras", email = "jose.cabrero@nillion.com" }
]
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "nuc==0.1.0rc3",
    "openai>=1.93.0",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[dependency-groups]
dev = [
    "pytest>=8.4.0",
    "pytest-cov>=6.2.1",
    "ruff>=0.11.13",
]
