[project]
name = "uvicorn-hmr"
version = "0.0.7.3"
readme = "README.md"
dependencies = [
    "hmr>=0.5.0,<0.7",
    "typer-slim>=0.15.4,<1",
    "uvicorn>=0.24.0",
]

[project.scripts]
uvicorn-hmr = "uvicorn_hmr:app"

[project.urls]
Homepage = "https://github.com/promplate/hmr"

[project.optional-dependencies]
all = [
    "fastapi-reloader~=1.0",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.uv.sources.fastapi-reloader]
workspace = true
