[tool.poetry]
name = "bagcheck"
version = "0.2.13"
description = "A pipeline validation tool for Concourse and GitHub Actions"
authors = ["John Carter <jfcarter2358@gmail.com>"]
readme = "README.md"
repository = "https://github.com/jfcarter2358/bagcheck"
keywords = ["concourse", "github-actions", "bagcheck"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
jsonpath-ng = "^1.5.3"
pyyaml = "^6.0"
rich-click = "^1.5.2"
requests = "^2.32.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
bagcheck = "bagcheck.bagcheck:cli"
