[project]
name = "quda-ml"
version = "0.2.7"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hydra-core>=1.3.2",
    "lightgbm>=4.6.0",
    "matplotlib>=3.10.3",
    "mlflow>=3.1.0",
    "omegaconf>=2.3.0",
    "pandas>=2.3.0",
    "polars>=1.31.0",
    "quda-core>=1.0.3",
    "scikit-learn>=1.7.0",
    "torch>=2.7.1",
    "tqdm>=4.67.1",
    "typer>=0.16.0",
    "ygo>=1.1.6",
]

license="MIT"
[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["quda.ml", "quda.ml.*", "quda.cli", "quda.cli.*", ]

[tool.setuptools.package-data]
"quda.ml.conf" = ["*.yaml", "**/*.yaml",]

[project.scripts]
quda = "quda.cli.main:app"
