[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "personalinfo"
version = "0.0.3"
authors = [
  { name="Prabaharan", email="prabaharanpython@gmail.com" },
]
description = "collection of personal information"
readme = "README.md"
requires-python = ">=3.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/prabaharanpython/personalinfo"
Issues = "https://github.com/prabaharanpython/personalinfo"
